language: android
dist: trusty
android:
  components:
  - build-tools-29.0.2
  - android-29

before_install:
- openssl aes-256-cbc -K $encrypted_a7697d0a408d_key -iv $encrypted_a7697d0a408d_iv
  -in keystore.jks.enc -out keystore.jks -d

script: "./gradlew assembleRelease"
